version: "3.9"


services:

  _base: &base
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: []
    volumes:
      - .:/app
    environment: &base-environment
      ENVIRONMENT: local

  bot: &bot
    <<: *base
    ports:
      - "127.0.0.1:8081:8081"
    entrypoint: ["docker/start.sh"]
    depends_on:
      - rabbitmq

  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    ports:
      - "127.0.0.1:5672:5672"
      - "15672:15672"        
    environment:
      RABBITMQ_DEFAULT_USER: $RABBITMQ_USER
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_PASS
      RABBITMQ_VHOSTS: $RABBITMQ_VHOST
        
          
  scheduler:
    <<: *base
    entrypoint: ["docker/scheduler.sh"]
    depends_on:
      - rabbitmq
          

