version: "3.9"


services:

  _base: &base
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: []
    volumes:
      - .:/app
    environment: &base-environment
      ENVIRONMENT: local

  bot: &bot
    <<: *base
    ports:
      - "8081:8081"
    entrypoint: ["docker/start.sh"]
    depends_on:
      - rabbitmq

  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    ports:
      - "5672:5672"
      - "15672:15672"        
    environment:
      RABBITMQ_DEFAULT_USER: $RABBITMQ_USER
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_PASS
      RABBITMQ_VHOSTS: $RABBITMQ_VHOST
        
          
  scheduler:
    <<: *base
    entrypoint: ["docker/scheduler.sh"]
    depends_on:
      - rabbitmq
          

  nginx:
      container_name: nginx
      restart: unless-stopped
      image: nginx
      ports:
          - 80:80
          - 443:443
      volumes:
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command:  certonly --webroot -w /var/www/certbot --force-renewal --email ${EMAIL} -d ${APP_BASE_URL} --agree-tos